## Test notebook

In [1]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..'))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
%matplotlib inline

Load all data from data directory.

In [ ]:
from src.data_loader import (
    find_data_dir,
    load_train_data,
    load_test_data,
    load_pngs,
    load_submission_template
)

# Get data directory
root = find_data_dir()

# Get training data and test covariates
train_all_drugs, train_all_opioids, train_all_stims = load_train_data(root)
test_cov = load_test_data(root)

In [16]:
test_cov

,period_id,jurisdiction,unemployment_rate,labor_force,temp_avg_f,precip_in,gtrends_overdose,gtrends_fentanyl,gtrends_naloxone,gtrends_opioid,gtrends_methamphetamine,state_doh_release
0,if5b8Sut,AK,4.8,367671.0,-2.1,NaN,49.13,61.12,60.10,49.04,34.17,Alaska Department of Health Pilots Drug Checki...
1,if5b8Sut,AL,2.7,2387810.0,48.0,2.91,55.49,69.02,67.87,55.39,38.59,Alabama Department of Public Health Warns Publ...
2,if5b8Sut,AR,4.3,1448666.0,44.7,0.82,57.80,71.90,70.70,57.70,40.20,Arkansas Department of Health Notes Increasing...
3,if5b8Sut,AZ,4.4,3814917.0,50.3,0.35,54.33,67.59,66.46,54.24,37.79,NaN
4,if5b8Sut,CA,5.5,19878043.0,49.9,5.15,52.02,64.71,63.63,51.93,36.18,California Department of Public Health Issues ...
...,...,...,...,...,...,...,...,...,...,...,...,...
352,yFh3wzPe,VT,NaN,NaN,64.4,1.34,55.44,74.09,64.87,56.29,40.81,NaN
353,yFh3wzPe,WA,NaN,NaN,68.1,1.18,54.39,72.70,63.65,55.22,40.04,Washington State Department of Health Issues P...
354,yFh3wzPe,WI,NaN,NaN,66.6,3.68,50.21,67.10,58.75,50.98,36.96,Wisconsin Department of Health Services Recogn...
355,yFh3wzPe,WV,NaN,NaN,70.3,1.77,73.22,97.86,85.68,74.34,53.90,West Virginia Department of Health and Human R...
356,yFh3wzPe,WY,3.3,287825.0,65.6,0.90,45.50,60.81,53.24,46.20,33.49,Wyoming Department of Health Warns of Xylazine...

In [14]:
df = pd.read_table(data_dir / "sample_submission.csv", sep = ",")
df

     row_id period_id jurisdiction overdose_category  rate_per_10000_ed_visits
0         0  aL5zkp6g           AK         all_drugs                       0.0
1         1  aL5zkp6g           AK       all_opioids                       0.0
2         2  aL5zkp6g           AK    all_stimulants                       0.0
3         3  aL5zkp6g           AL         all_drugs                       0.0
4         4  aL5zkp6g           AL       all_opioids                       0.0
..      ...       ...          ...               ...                       ...
913     913  if5b8Sut           WV       all_opioids                       0.0
914     914  if5b8Sut           WV    all_stimulants                       0.0
915     915  if5b8Sut           WY         all_drugs                       0.0
916     916  if5b8Sut           WY       all_opioids                       0.0
917     917  if5b8Sut           WY    all_stimulants                       0.0

[918 rows x 5 columns]

In [7]:
X_raw

,period_id,jurisdiction,unemployment_rate,labor_force,temp_avg_f,precip_in,gtrends_overdose,gtrends_fentanyl,gtrends_naloxone,gtrends_opioid,gtrends_methamphetamine,state_doh_release
0,OqDkgaDk,AK,4.5,358314.0,NaN,NaN,50.66,63.50,57.20,49.56,36.89,Alaska Department of Health Authorizes Expande...
1,OqDkgaDk,AL,2.9,2341587.0,43.3,7.66,57.22,71.71,64.61,55.97,41.66,NaN
2,OqDkgaDk,AR,3.4,1398700.0,36.1,7.58,59.60,74.70,67.30,58.30,43.40,NaN
3,OqDkgaDk,AZ,3.5,3715794.0,42.1,1.37,56.02,70.22,63.26,54.80,40.80,Arizona Department of Health Services Announce...
4,OqDkgaDk,CA,5.1,19611227.0,45.7,4.63,53.64,67.23,60.57,52.47,39.06,California Department of Public Health Launche...
...,...,...,...,...,...,...,...,...,...,...,...,...
3922,shDD7wDP,VT,2.0,352691.0,41.2,5.59,51.41,20.56,25.65,71.87,33.28,NaN
3923,shDD7wDP,WA,4.4,3925819.0,46.3,3.50,50.44,20.18,25.17,70.51,32.66,Washington State Department of Health Warns Pu...
3924,shDD7wDP,WI,3.2,3115332.0,42.4,3.72,46.56,18.62,23.23,65.09,30.14,Wisconsin Department of Health Services Expand...
3925,shDD7wDP,WV,4.8,789004.0,54.9,3.85,67.90,27.16,33.88,94.92,43.96,West Virginia Department of Health and Human R...
3926,shDD7wDP,WY,3.5,292522.0,41.1,1.97,42.20,16.88,21.05,58.99,27.32,Wyoming Department of Health Expands Access to...